version: 2
jobs:
  build:
    parallelism: 4
    working_directory: ~/rails-api-skeleton
    docker:
      - image: circleci/ruby:2.5.0
        environment:
          RAILS_ENV: test
      - image: circleci/mysql:5.7.17
        environment:
          MYSQL_ROOT_HOST: '%'
          MYSQL_ALLOW_EMPTY_PASSWORD: true

    steps:
      - checkout

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      # Restore bundle cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-

      # Setting up application
      - run:
          name: Setup application
          command: bin/setup

      # Store bundle cache
      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Run Brakeman
      - run:
          name: Brakeman
          command: bundle exec brakeman --no-progress --separate-models --exit-on-warn

      # Run Rubocop
      - run:
          name: Rubocop
          command: bundle exec rubocop

      # Run RSpec in parallel
      - run:
          name: Run Tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec

      # Circle CI Reports
      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
